### ISSUE TITLE
Option to always report logs

### ISSUE THREAD

**Issue by The-Compiler** [eisensheng/pytest-catchlog#1]
Hi!

In 19ff0645a910a0a7d545e7e0baf7eed350ddb93c you mention:

> A far better approach would be to replace this option with an
> 
> ```
>     --report-logs=[never,failed,always]
> ```
> 
> option though.

For my project, I use a buildbot which marks the tests as "warning" when there was logging output. I also use debug logging a lot, so ideally I'd be able to do something like this:
- Report log entries with debug/info level when a test failed.
- Always report log entries with warning/error/critical levels.

If something like that would be a welcome addition, please let me know and I'll submit a pull request!

Inputs on how the configuration would look would be welcome though. Maybe keep `--no-print-logs` and then add `--loglevel-pass` and `--loglevel-fail` or something?

**Comment by eisensheng** [comment]
Hi!

Thanks for your input. My memory on this project is a little cloudy. IIRC the primary need for me to work on this library was the requirement to ensure that the application logs certain events and thus the log lines had to be caught. Now you're proposing a second use case for this library to catch any log lines and output logs for failing tests. 

I like the idea since it seems to me to be very useful and thus would love to see a patch for it and also would merge it if you would be so kind to provide one. I would suggest a different approach to it though to keep the explanation of the feature simple. I'll try to collect some thoughts on this here:
- I think it is always a desired behavior to receive all logged events for a failed test IMHO. Following that thought means there is no need to configure a minimum level for failed tests. 
- It would also be nice to still be able to silence the log output altogether so you won't litter the logs on your CI system.
- It would still be nice to see logs of a certain level on your local development system to spot possible errors. 
- To enable the behavior on a global scope that any log output may lead to a non successful state of the test seems not that good to me TBH. It may even be the case that an error event here and a warning event there is totally fine because you're testing a fallback behavior for a failed condition. If this scenario stays valid it means that a global configuration for this may not fit the need of all your tests. The need to fail tests if an error/warning/critical event was caught can be realized through an assert though.

It seems to me to be quite the difficult endeavor and there is further need to iron out the remaining wrinkles in the proposal. I hope the text was understandable and constructive to you and didn't kill your motivation regarding this issue. It was a tiresome workday for me so I might have overlooked something. I would thank you if you could stay patient with me and point it out to me then. Thanks!

**Comment by The-Compiler** [comment]
I agree with the first three points! So the only thing needed from an UI perspective would be some option to set a minimum loglevel to always show, right?

For the fourth point, that's not what I'm proposing - I just want to see the log output on stdout, and my CI will interpret that as "warnings" (as opposed to success/failure). So from the perspective from a pytest-catchlog user, the tests will still all pass.

**Comment by eisensheng** [comment]
> I agree with the first three points! So the only thing needed from an UI perspective would be some option to set a minimum loglevel to always show, right?

Yes. :smiley: 

> For the fourth point, that's not what I'm proposing - I just want to see the log output on stdout, and my CI will interpret that as "warnings" (as opposed to success/failure). So from the perspective from a pytest-catchlog user, the tests will still all pass.

That's also okay. I guess everything has been settled then. I wish you good luck and some fun on coding. :wink:

**Comment by The-Compiler** [comment]
Just a small update: I didn't have time to work on this so far - and I'm also wondering about alternative solutions so this will work without the CI setup as well (like an option or maybe a separate plugin which fails a test when there are unexpected log messages).

**Comment by The-Compiler** [comment]
I ended up writing some code to fail a test when there's an unexpected logging message - so I'm afraid I won't work on this anymore, so I'm closing it.
