### ISSUE TITLE
Please included tests in pypi release

### ISSUE THREAD

**Issue by jlec** [eisensheng/pytest-catchlog#13]
Downstream developer love to test during their installation process. Please include the tests in the pypi tarball.

**Comment by eisensheng** [comment]
I understand your pain. Testing the integrity of an entire distribution of multiple packages is hard.

My general stance towards PYPI used to be that packages go there to be installed, through PIP for example. Not to be redistributed and tested somewhere else. This is where the release archives provided by Github comes into play. 

Since PYPI also offers a "Source Distribution" of the given package for download and thus having two different flavors of a Source Distribution that comes from Github and the Source Distribution that comes from the PYPI is bad. This is terrible to be honest. Thanks for pointing this out. I didn't realize that before.

My propose for this issue thus would be to keep both Source Distributions the same but do not install the test suite through PIP or other means. Does this sound acceptable for you? If an agreement can't be reached I would also be in to drop my stance and just install the test suite together with the plugin itself.

**Comment by jlec** [comment]
Probably you got me wrong. I would like to have the tests contained in the pypi tarball, but _not_ installed using pip. We are fetching the tarball, running `python setup.py build`, running the tests according to how upstreams test (e.g. through travis) and running `python setup.py install`. So we only need the tests contained in the tarball not installed to the system

**Comment by abusalimov** [comment]
@jlec Could you help us and specify what exactly we should add into `setup.py`? Honestly, (personally) I'm a kind of setuptools newbie. Any link to a package with a "good" `setup.py` as an example would be fine too. Thanks.

**Comment by eisensheng** [comment]
@abusalimov We should patch MANIFEST.in to include the test files. I was already playing around with this yesterday.

**Comment by abusalimov** [comment]
Ah, awesome!
I'll assign this to you then, OK?
