### ISSUE TITLE
Live logging settings missing from help text and unavailable at command line

### ISSUE THREAD

**Issue by smallnamespace** [eisensheng/pytest-catchlog#63]
I'm running into the same problem as https://github.com/eisensheng/pytest-catchlog/issues/51.

In particular, I see this in a freshly installed conda env with py3.6, pip, and pytest only, and I'm unable to see the cli options even running from the site-packages dir. Attempting to use `--log-level` works, but `--log-cli-level` and the like result in flag not found errors.

**Comment by maxkondel** [comment]
Because they didn't released new version for pypy for 1.5 years already, and --log-cli-level merged only half years ago. Use master instead.

**Comment by dfee** [comment]
Oh man. This just bit me too.

I'll expand this so that others might understand if this problem affects them –

This problem affects you, if:
- you are using `log_cli_level` in your `pytest.ini`
- you are passing `--log-level-cli` to pytest and you receive "pytest: error: unrecognized arguments: --log-cli-level INFO"

For convenience, install master like this: `pip install git+https://github.com/eisensheng/pytest-catchlog#egg=pytest-catchlog`

**Comment by smallnamespace** [comment]
Dumb question -- why the long delay in releases? I see some extant tickets to merge this with other projects, but has that actually happened?

**Comment by lloydaduke** [comment]
Also bitten.
Thanks @dfee for the Google bait that I hope gets indexed soon.
Thanks @maxkondel for the suggestion.

**Comment by The-Compiler** [comment]
Since this was fixed in `development`, and the pytest-catchlog plugin (the `development` branch) was merged into the pytest core, this probably isn't applicable anymore.
